apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-ui-backend-rb
  namespace: default
subjects:
  - kind: ServiceAccount
    name: k8s-ui-backend-sa
    namespace: default
roleRef:
  kind: Role
  name: k8s-ui-backend-role
  apiGroup: rbac.authorization.k8s.io
