# templates/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ui-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: k8s-ui-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: k8s-ui-frontend
  template:
    metadata:
      labels:
        app: k8s-ui-frontend
    spec:
      volumes:
        - name: nginx-conf
          configMap:
            name: k8s-ui-frontend-nginx
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
