apiVersion: v1
kind: Service
metadata:
  name: k8s-ui-frontend
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.frontend.serviceType | default "LoadBalancer" }}
  selector:
    app: k8s-ui-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  {{- if and (.Values.frontend.loadBalancerIP) (ne .Values.frontend.loadBalancerIP "") }}
  loadBalancerIP: {{ .Values.frontend.loadBalancerIP }}
  {{- end }}
